version: '3'
tasks:
  default:
    desc: Build the go binary.
    cmds:
      - task --list-all

  hello:
    cmds:
      - echo "I am going to write a file named 'output.txt' now."
      - echo "hello" > output.txt
    generates:
      - output.txt
