// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"passkey-demo/internal/repository"
	"passkey-demo/internal/repository/dao"
	"passkey-demo/internal/service"
	"passkey-demo/internal/web"
	"passkey-demo/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	v := ioc.InitGinMiddlewares()
	userHandler := web.NewUserHandler()
	logger := ioc.InitLoggerSlog()
	serviceService := ioc.InitWebauthn()
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewCachedUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	webauthnHandler := web.NewWebauthnHandler(logger, serviceService, userService)
	engine := ioc.InitWebServer(v, userHandler, webauthnHandler)
	app := &App{
		web: engine,
	}
	return app
}
